channels:
  - conda-forge

dependencies:
  - jupyterhub-singleuser

  # Everyone wants to use nbgitpuller for everything, so let's do that
  - nbgitpuller
  # Install packages from pip
  - pip
  - pip:
    - globus-sdk
